name       : moc
version    : 2.5.2
release    : 10
source     :
    - http://ftp.daper.net/pub/soft/moc/stable/moc-2.5.2.tar.bz2 : f3a68115602a4788b7cfa9bbe9397a9d5e24c68cb61a57695d1c2c3ecf49db08
license    : GPL-2.0
component  : multimedia.audio
summary    : MOC (music on console) is a console audio player.
description: |
    MOC (music on console) is a console audio player for LINUX/UNIX designed to be powerful and easy to use.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(flac)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(ncursesw)
    - pkgconfig(ogg)
    - pkgconfig(popt)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - faad-devel
    - libid3tag-devel
    - libmad-devel
    - mpc-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm644 $pkgfiles/moc@.service $installdir/etc/systemd/system/moc@.service
