name       : moc
version    : 2.5.1
release    : 5
source     :
    - http://ftp.daper.net/pub/soft/moc/stable/moc-2.5.1.tar.bz2 : 1b419c75a92a85ff4ee7670c65d660c86fef32032c65e89e868b988f80fac4f2
license    : GPL-2.0
component  : multimedia.audio
summary    : MOC (music on console) is a console audio player.
description: |
    MOC (music on console) is a console audio player for LINUX/UNIX designed to be powerful and easy to use.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(flac)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libmodplug)
    - pkgconfig(ncursesw)
    - pkgconfig(ogg)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(speex)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - faad-devel
    - libid3tag-devel
    - libmad-devel
    - mpc-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -Dm644 $pkgfiles/moc@.service $installdir/etc/systemd/system/moc@.service
